baseURL = "/"
languageCode = "en-US"
title = "Behind The Scenez Tattooz"
theme = "moderntattoo"

copyright = "Â© 2020 Behind The Scenez Tattooz"

[deployment]

[[deployment.targets]]
name = "s3"
URL = "s3://behindthescenezttatooz.com?region=us-west-2"
